### ISSUE TITLE
vCenter Reachability check fails with DNS name.

### ISSUE THREAD

**Issue by sttardy** [CiscoDevNet/Hyperflex-Hypercheck#14]
The "else" section around line 827 is not correct if using a DNS name instead of an IP.
The code is evaluating to roughly:
`"vCenterURL: https://myvcenter.example.com".split(":")[1].replace("https://", "").strip()  `
which returns "https" instead of "https://myvcenter.example.com"

Can fix by changing line:
`l = line.split(":")  `
to add a space after the : like:
`l = line.split(": ")  `

**Comment by avshukla** [comment]
Thanks! I realized I missed a space after : , updated the script
