### ISSUE TITLE
No handlers could be found for logger "paramiki.transport"

### ISSUE THREAD

**Issue by sttardy** [CiscoDevNet/Hyperflex-Hypercheck#15]
HyperCheck on HX 2.1(1b) with ESXi 6.0u2 build 3620759 outputs:
```
No handlers could be found for logger "paramiki.transport"
Not able to establish SSH connection to ESXi Host: 192.0.2.11
Invalid ESX root password
```
Password is verified to be correct as password was copy/pasted and same copy/pasted password works using the OpenSSH binary `ssh root@192.0.2.11`.
HyperCheck log shows:
> 03-26-2020 06:25:43 - HX_TOOL - ERROR - Incompatible ssh peer (no acceptable kex algorithm)

`pip show paramiko` shows bad paramiko version 1.7.7.1 is in use.

Workaround: None

Could detect this condition within HyperCheck and fallback to using `ssh` binary, but would require some code rework.

**Comment by avshukla** [comment]
Looking into it. Will update with progress.

**Comment by fjacquet** [comment]
similar here

```
 python HXTool.py detail

                 HX Health Check 3.8

    The script in use might be old. Please check and confirm that this is the latest script on Github.

Please enter below info of HX-Cluster:
Option: detail

**No handlers could be found for logger "paramiko.transport"**
Not able to establish SSH connection to HX Node: 10.80.0.111
Invalid HX root password

```

sound a regresssion also that  it use the controller data address (eth1) instead of controller address (eth0)

in my case 
```
$ pip show paramiko
Name: paramiko
Version: 2.6.0
Summary: SSH2 protocol library
Home-page: https://github.com/paramiko/paramiko/
Author: Jeff Forcier
Author-email: jeff@bitprophet.org
License: LGPL
Location: /usr/local/lib/python2.7/dist-packages
Requires: bcrypt, pynacl, cryptography
You are using pip version 9.0.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

We use 4.0.2a

**Comment by avshukla** [comment]
Thanks Frederic. We have seen this exact same error for a cluster where ESXI ssh was disabled on all nodes and CMIP was not able to run stMgr commands.

We are adding check to make it more robust. Expect updates by next week.

Regards,
Avinash

**Comment by fjacquet** [comment]
As I said. 

Our ssh is open and our issue is on HX root 

Eth1 instead of eth0 is more a concern for me 

Send from my phone

**Comment by avshukla** [comment]
Hi Frederic,

For ESXi we use vmk0. For SCVMs we use eth1. What is your concern here?

Regards,
Avinash

**Comment by fjacquet** [comment]
Here on scvm, eth0:mgmt is management VIP, eth0 normal management, eth1 is data access so … I am surprised you use “private” IP (for storage access)

Is my config nonstandard ?

Regards
Fred

De : Avinash Shukla <notifications@github.com>
Répondre à : CiscoDevNet/Hyperflex-Hypercheck <reply@reply.github.com>
Date : mardi, 28 avril 2020 à 20:19
À : CiscoDevNet/Hyperflex-Hypercheck <Hyperflex-Hypercheck@noreply.github.com>
Cc : Frederic Jacquet <fred.jacquet@gmail.com>, Comment <comment@noreply.github.com>
Objet : Re: [CiscoDevNet/Hyperflex-Hypercheck] No handlers could be found for logger "paramiki.transport" (#15)

Hi Frederic,

For ESXi we use vmk0. For SCVMs we use eth1. What is your concern here?

Regards,
Avinash

**Comment by avshukla** [comment]
Hi Fred,

We are using private IP to SSH between SCVM because we don’t know what network firewalls might be in place. Eth1 being internal helps with that.

I am still not clear what is your concern here? Are you unable to run Hypercheck on your cluster? Please confirm if your ESXi password is correct and SSH is enabled.

Regards,
Avinash

**Comment by fjacquet** [comment]
My main concern is that the script does not run in my environment. 

root@SpringpathControllerXTQYPM4CIH:/home/admin/Hyperflex-Hypercheck-master# python HXTool.py

                 HX Health Check 3.8

    The script in use might be old. Please check and confirm that this is the latest script on Github.

Please enter below info of HX-Cluster:
Enter the HX-Cluster Root Password:
Enter the ESX Root Password:

No handlers could be found for logger "paramiko.transport"
Not able to establish SSH connection to HX Node: 10.80.0.111
Invalid HX root password
root@SpringpathControllerXTQYPM4CIH:/home/admin/Hyperflex-Hypercheck-master# ssh root@10.80.0.111
Operating in CiscoSSL FIPS mode
FIPS mode initialized
The authenticity of host '10.80.0.111 (10.80.0.111)' can't be established.
ECDSA key fingerprint is SHA256:OkA9czzcL7I5fYbfLNtSI+D+Ng5dYp15qk/9C1cQzzk.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '10.80.0.111' (ECDSA) to the list of known hosts.
 HyperFlex StorageController 4.0(2a)
root@10.80.0.111's password:
---------------------------------------------------------
                   !!! ALERT !!!
This service is restricted to authorized users only.
All activities on this system are logged. Unauthorized
access will be reported.
---------------------------------------------------------


 HyperFlex StorageController 4.0(2a)
Last login: Wed Apr 29 09:09:13 2020 from 172.16.1.105

**Comment by fjacquet** [comment]
Weird ... I have been able to run after relocating the script from /home/admin to /tmp ... 

so I don't understand anymore

**Comment by hxkiran** [comment]
Workaround for this issue is uninstall and install cryptography module.
> python -m pip  uninstall cryptography
> python -m pip  install cryptography

**Comment by hsardana09** [comment]
Fix cannot be added to Hypercheck, workaround:
Workaround for this issue is uninstall and install cryptography module.

    python -m pip uninstall cryptography
    python -m pip install cryptography
