### ISSUE TITLE
Missing ESXi_vmk1 and CtrlVM_eth1 1500 vs 9000 MTU check

### ISSUE THREAD

**Issue by sandkum5** [CiscoDevNet/Hyperflex-Hypercheck#16]
The code is missing check for 1500 vs 9000 MTU check for CtrlVM_eth1 and ESXi_vmk1 interfaces. 

Some customers are using 1500 MTU for data interfaces(eth1 and vmk1) and the ping test fails for those customers even though it's as per the design and there is no ping drop issue.

**Comment by hsardana09** [comment]
Check added in the updated/committed build.
