### ISSUE TITLE
vib name change with 4.0.2a 

### ISSUE THREAD

**Issue by sandkum5** [CiscoDevNet/Hyperflex-Hypercheck#17]
With 4.0.2a code, we have changed the VIB Names. Hence, the command "grep -i spring" wont list the vibs.. 
It should be replaced with "egrep -i "spring|cis". 

Sample output: 
#esxcli software vib list | grep -i cis
scvmclient                   4.0.2-12                              			CIS     VMwareAccepted    2020-04-11
stHypervisorSvc          4.0.2-11                              			CIS     VMwareAccepted    2020-04-11
vmware-esx-STFSNasPlugin   4.0.2-12                              	CIS     VMwareAccepted    2020-04-11
ucs-tool-esxi                1.1.0-1OEM                            	        CIS     PartnerSupported  2020-04-11

**Comment by hsardana09** [comment]
Check added in the updated/committed build.
