### ISSUE TITLE
HyperCheck should check ESXi vfat disk space.

### ISSUE THREAD

**Issue by sttardy** [CiscoDevNet/Hyperflex-Hypercheck#19]
If any of the three ESXi vfat disks are full, then ESXi upgrades will fail with error like:
> Upgrading hypervisor. 
> ESXi upgrade failed on host 192.0.2.1. Failed to apply profile HX-ESXi-6.7U3-15160138-Cisco-Custom-6.7.3.3

HyperCheck can detect this with ESXi command: 
    `df -h | grep vfat | grep 100%`
In this failed upgrade instance it was partial files which had to be removed:
    /vmfs/volumes/<UUID>/packages/*/vmtools/*.filepart

**Comment by hsardana09** [comment]
Check added in the updated/committed build.
