### ISSUE TITLE
ver = l[1] IndexError: list index out of range

### ISSUE THREAD

**Issue by christung16** [CiscoDevNet/Hyperflex-Hypercheck#2]
when execute HXTool.py
It returns error, any clue how to fix it??

root@SpringpathController69QJTK8EP7:~/Hyperflex-Hypercheck-master# python HXTool.py

                 HX Health Check 3.0

Please enter below info of HX-Cluster:
Enter the HX-Cluster Root Password:
Enter the ESX Root Password:

SSH connection established to HX Node: 10.74.202.55
SSH connection established to HX Node: 10.74.202.56
SSH connection established to HX Node: 10.74.202.57

HX Cluster Nodes:
+-------+--------------+--------------------------------+
| Nodes | IP Address   | HostName                       |
+-------+--------------+--------------------------------+
| 1     | 10.74.202.55 | SpringpathController69QJTK8EP7 |
+-------+--------------+--------------------------------+
| 2     | 10.74.202.56 | SpringpathControllerFFZY91R0KF |
+-------+--------------+--------------------------------+
| 3     | 10.74.202.57 | SpringpathController23J9GAZ7PG |
+-------+--------------+--------------------------------+

('pk: ', u'storfs-appliance                     4.0.1a-33028')
('pk: ', u'storfs-asup                          4.0.1a-33028')
('pk: ', u'storfs-core                          4.0.1a-33028')
('pk: ', u'storfs-fw')
Traceback (most recent call last):
  File "HXTool.py", line 1558, in <module>
    ver = l[1]
IndexError: list index out of range
root@SpringpathController69QJTK8EP7:~/Hyperflex-Hypercheck-master#

**Comment by avshukla** [comment]
Hi Chris,

Can you share the HX_Report tar bundle?

Regards,
Avinash

**Comment by avshukla** [comment]
This issue should be resolved. I have merged the updated script.
