### ISSUE TITLE
SSL Certificate check

### ISSUE THREAD

**Issue by fjacquet** [CiscoDevNet/Hyperflex-Hypercheck#21]
Hello

After 4.0.2a upgrade we had only some ssl certificates change, not everyone on the cluster.

This script (version 3.8) have not detect (I don't think it check) but I think it (sh|c)ould.

In our case, it has been fixed with TAC

Thanks
Fred

**Comment by avshukla** [comment]
Yes, that’s a new issue.  Please be cognizant that Hypercheck doesn’t solve or flag all known/existing issues. It performs as documented list of checks to determine the cluster health state.s

Regards,
Avinash

**Comment by hsardana09** [comment]
UN-reproducable, hence a fix cannot be added.
