### ISSUE TITLE
Check SCVM plugin version

### ISSUE THREAD

**Issue by gemirand** [CiscoDevNet/Hyperflex-Hypercheck#22]
As scvmclient is not always upgraded, depending on source/destination version of HXDP upgrade, this check can sometimes gives a false fail.

**Comment by kebrant** [comment]
> As scvmclient is not always upgraded, depending on source/destination version of HXDP upgrade, this check can sometimes gives a false fail.

What can be checked to determine if this is a false fail or something to remediate?

**Comment by avshukla** [comment]
yes we are updating this check in the next commit.

**Comment by hsardana09** [comment]
Check has been removed in the updated/committed build as it had multiple false alarms.
