### ISSUE TITLE
"getLocalNode.sh"  may take more than 30 secs to run

### ISSUE THREAD

**Issue by mridul81** [CiscoDevNet/Hyperflex-Hypercheck#24]
On few SCVMs the  script " /opt/springpath/storfs-mgmt-cli/getLocalNode.sh " may take more than the 30 sec timeout to run and hence the Esxi eth0 IP is not fetched.

Command output is "Not able to run the command" presently.
Logs attached .

[HX_Report_02_05_2020_03_40_43.zip](https://github.com/CiscoDevNet/Hyperflex-Hypercheck/files/4585402/HX_Report_02_05_2020_03_40_43.zip)

**Comment by hsardana09** [comment]
Fix cannot be provided in 4.0, from 4.5 onward the script will use restapi instead of getLocalNode.sh
