### ISSUE TITLE
vmk0 IPs must be verified before running network checks

### ISSUE THREAD

**Issue by mridul81** [CiscoDevNet/Hyperflex-Hypercheck#25]
Vmk0 outputs must be verified ( to be in the format of a valid IP address) before an attempt to SSH to that Esxi host and/or running any related network checks .

Example of current scenario 

vmk0: 172.18.196.31, **Not able to run the command**, 172.18.196.33
........
vmkping -I vmk0 -c 3 -d -s 1472 -i 0.05 **Not able to run the command**

**Comment by hsardana09** [comment]
Mgmt pings have been removed in the updated/committed build.
