### ISSUE TITLE
Check SCVMs have matching springpath_keystore.jceks

### ISSUE THREAD

**Issue by sttardy** [CiscoDevNet/Hyperflex-Hypercheck#26]
Upgrades can fail with generic errors:
```
Checking if all controller VMs have enough free space in root partition
Failed to run command on remote node: EntityRef(5d45df91-096e-41db-bd30-4d251590f1f2,Node,Some(Cluster-HX01),None,None)
```

HyperCheck can run command on all SCVMs:
  > `md5sum /etc/springpath/secure/springpath_keystore.jceks`

And compare output across all SCVMs to make sure the files match.

**Comment by hsardana09** [comment]
Check added in the updated/committed build.
