### ISSUE TITLE
Timestamps should follow ISO 8601

### ISSUE THREAD

**Issue by sttardy** [CiscoDevNet/Hyperflex-Hypercheck#27]
HyperCheck timestamps should follow [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) for consistency and ease-of-use.

Several lines like:
`    dir_name = "HX_Report_" + str(cdate.strftime("%d_%m_%Y_%H_%M_%S"))`
and
`    return (datetime.datetime.now().strftime("%d-%m-%Y_%I-%M-%S"))`
and
`    formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s', '%m-%d-%Y %I:%M:%S')`
and
`                ipdt = datetime.datetime.strptime(d, "%m/%d/%y %H:%M:%S")`
and
`                            jpdt = datetime.datetime.strptime(jd, "%m/%d/%y %H:%M:%S")`

Should follow format **YYYY-MM-DDThh:mm:ss**

**Comment by hsardana09** [comment]
Timestamp corrected in the updated/committed build.
