### ISSUE TITLE
Timestamp check FAIL

### ISSUE THREAD

**Issue by sttardy** [CiscoDevNet/Hyperflex-Hypercheck#3]
Timestamp checks seems to be false failure.
Clusters with more (10) than a few (4-5) nodes and the timestamp check has line 1531:
"""
        time.sleep(30)
"""
Seems like this is sleeping adding delay causing timestamps between nodes to be exactly 30 seconds apart.

**Comment by avshukla** [comment]
Thanks Steven. Correct. I hit this issue too, we are doing sequential check.Working on fixing it. I will upload the latest  script once done.

**Comment by avshukla** [comment]
Fix for “Timestamp” check. Now separate thread is used to check this. Updated the script.
