### ISSUE TITLE
/tmp dir permission failure 

### ISSUE THREAD

**Issue by sandkum5** [CiscoDevNet/Hyperflex-Hypercheck#30]
As per hypecheck code, we are doing the following match: 
if line.startswith("drwxr-xrwx"):
            tmprcheck = "PASS"
        else:
            tmprcheck = "FAIL"

In my customer case, the /tmp directory has drwxrwxrwx(777) permissions which should be ok but because of the above match, it's causing a failure. 

We should match against a list of required permissions rather than a specific match to avoid failures in customer environments.

**Comment by hsardana09** [comment]
Check added in the updated/committed build.
