### ISSUE TITLE
USB0 Check add `lsusb` output

### ISSUE THREAD

**Issue by sttardy** [CiscoDevNet/Hyperflex-Hypercheck#34]
In instances of failures of **USB0 Check**, then output of `lsusb` from SCVM and ESXi are needed to troubleshoot further.
If .log file included `lsusb` output, then troubleshooting steps would be known.

Please add `lsusb` output to .log file from both ESXi and SCVM.

**Comment by afrahmad** [comment]
Thanks for the feedback Steven .We have added the check # if UCSB0 check fail , we are capturing the "lsusb" in the logs for Troubleshooting
