### ISSUE TITLE
"Check the dump in springpathDS" Fail

### ISSUE THREAD

**Issue by mnagamori** [CiscoDevNet/Hyperflex-Hypercheck#7]
The output of "esxcli hardware platform get | grep -i serial" is different from ESXi6.7.
This command seems to be used in the script to get UCS S/N.
As a result, "Check the dump in springpathDS" will fail when this tool is executed on ESXi 6.7.

**Comment by avshukla** [comment]
Thanks for the feedback. Added fix in the latest commit.
