### ISSUE TITLE
vmotion test with -S vmotion fails on HyperCheck 3.6

### ISSUE THREAD

**Issue by thetopnach** [CiscoDevNet/Hyperflex-Hypercheck#8]
Looks like the vmotion kvm check has flag for vmotion stack. 
vmkping -I vmk2 -c 3 -d -s 8972 192.168.208.12 -S vmotion
*** vmkernel stack not configured ***

If -S vmotion is removed, ping is successful. 
[root@hx-01-esxi-01:~] vmkping -I vmk2 -c 3 -d -s 8972 192.168.208.12
PING 192.168.208.12 (192.168.208.12): 8972 data bytes
8980 bytes from 192.168.208.12: icmp_seq=0 ttl=64 time=0.312 ms
8980 bytes from 192.168.208.12: icmp_seq=1 ttl=64 time=0.174 ms

**Comment by avshukla** [comment]
Fixed in latest
