### ISSUE TITLE
Add check for clusterAccessPolicy set to lenient vs strict - critical check for HX 1.7.1/1.8 clusters

### ISSUE THREAD

**Issue by thetopnach** [CiscoDevNet/Hyperflex-Hypercheck#9]
If clusterAccessPolicy is set to strict, FAIL check. Provide steps to change to lenient.

root@hx-01-scvm-01:/tmp/Hyperflex-Hypercheck-master# stcli cluster storage-summary
address: 192.168.204.10
name: RCH-HX-01
state: online
uptime: 20 days 22 hours 10 minutes 16 seconds
activeNodes: 3 of 3
compressionSavings: 34.64%
deduplicationSavings: 0.15%
freeCapacity: 6.0T
healingInfo:
    inProgress: False
resiliencyInfo:
    messages:
        Storage cluster is healthy.
    state: 1
    nodeFailuresTolerable: 1
    cachingDeviceFailuresTolerable: 2
    persistentDeviceFailuresTolerable: 2
    zoneResInfoList: None
spaceStatus: normal
totalCapacity: 6.0T
totalSavings: 34.74%
usedCapacity: 70.6G
zkHealth: online
clusterAccessPolicy: lenient <----
dataReplicationCompliance: compliant
dataReplicationFactor: 3
root@hx-01-scvm-01:/tmp/Hyperflex-Hypercheck-master#

**Comment by avshukla** [comment]
Good feedback. Will get it added to version 3.9.
